### ISSUE TITLE
Highlight vanishes when I move to another file

### ISSUE THREAD

**Issue by miwel04** [balmacefa/line_highlight_bookmark_vscode#3]
Hey, thanks for the extensions, works pretty well and I like that the bookmark jumps do NOT remember insertion order.
However I would like the line highlight to stay ON always.
It vanishes when I go to another application window, or when I go to another file in VScodium window.
My data (VS codium):
Version: 1.55.1 (system setup)
Commit: 08a217c4d27a02a5bcde898fd7981bda5b49391b
Date: 2021-04-09T00:50:25.642Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by balmacefa** [comment]
Yes, it's a little annoying. I'll free some time at weekend to work on this.

**Comment by miwel04** [comment]
> Yes, it's a little annoying. I'll free some time at weekend to work on this.

That would be amazing. Either way it is helpful as it is. Thank you

**Comment by balmacefa** [comment]
@miwel04 Fixed! Hope you feel more productive!

**Comment by miwel04** [comment]
wow works perfect, simple and effective. thanks a lot
