### ISSUE TITLE
Add bookmark color for minimap

### ISSUE THREAD

**Issue by Haqimzuhari** [balmacefa/line_highlight_bookmark_vscode#7]
Hello.
Current version is already great. Bookmark icon is so big. Easy to see
I wonder if you able to add this bookmark some highlight in minimap as well.
We can already see where is the bookmarked line in minimap and can jump right to it instantly. 
I think that the good feature i guess. 

Thanks alot man. may have a great day ahead.

**Comment by balmacefa** [comment]
Yeah, that would be useful. I may need to look at the docs...👨‍🎓💻
Not know if would have the time, open to **pr** if you want to contribute.
